---
- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create authorized_keys file with correct permissions if it doesn't exist
  file:
    path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
    state: touch
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  changed_when: false

- name: Add SSH public keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "*.pub"

