---
- name: Install can-logger
  hosts: all
  become: yes

  tasks:
  - name: Ensure pip is installed
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: Install can-logger by pip
    pip:
      name: can-logger
      extra_args: "--break-system-packages --ignore-installed"
      state: latest
      executable: pip3